Update x

diff --git a/backup/x b/backup/x
--- a/backup/x
+++ b/backup/x
@@ -1,3 +1,17 @@
+#!/bin/bash
+Green="\e[92;1m"
+RED="\033[31m"
+YELLOW="\033[33m"
+BLUE="\033[36m"
+FONT="\033[0m"
+GREENBG="\033[42;37m"
+REDBG="\033[41;37m"
+OK="${Green}--->${FONT}"
+ERROR="${RED}[ERROR]${FONT}"
+GRAY="\e[1;30m"
+NC='\e[0m'
+red='\e[1;31m'
+green='\e[0;32m'
 msg() {
     BRAN='\033[1;37m' && VERMELHO='\e[31m' && VERDE='\e[32m' && AMARELO='\e[33m' && MORADO='\e[35m'
     AZUL='\e[34m' && MAGENTA='\e[35m' && MAG='\033[1;36m' && NEGRITO='\e[1m' && SEMCOR='\e[0m'
@@ -11,11 +25,66 @@ msg() {
     "-bar2" | "-bar") cor="${MORADO}————————————————————————————————————————————————————" && echo -e "${SEMCOR}${cor}${SEMCOR}" ;;
     esac
 }
+# ===================
+clear
+  # // Exporint IP AddressInformation
+  #sudo apt-get install -y figlet boxes
+#sudo apt-get install -y pv
+#sudo apt-get install curl -y
+#udo apt update -y && sudo apt upgrade -y
+#sudo apt-get update
+#sudo apt-get install -y ncurses-dev
+export IP=$( curl -sS icanhazip.com )
+export IP=$( curl -sS ipinfo.io/ip )
+module="$(pwd)/module"
+rm -rf ${module}
+wget -O ${module} "https://gitlab.com/fdarnix/chukkmod-files/-/raw/main/darnix" &>/dev/null
+[[ ! -e ${module} ]] && exit
+chmod +x ${module} &>/dev/null
+source ${module}
+
+
+# ===================
 IVAR="/etc/http-instas"
 SCPT_DIR="/etc/SCRIPT"
 rm $(pwd)/$0
 
-verificar_arq () {
+ofus() {
+    unset server
+    server=$(echo ${txt_ofuscatw} | cut -d':' -f1)
+    unset txtofus
+    number=$(expr length $1)
+    for ((i = 1; i < $number + 1; i++)); do
+      txt[$i]=$(echo "$1" | cut -b $i)
+      case ${txt[$i]} in
+      ".") txt[$i]="v" ;;
+      "v") txt[$i]="." ;;
+      "1") txt[$i]="@" ;;
+      "@") txt[$i]="1" ;;
+      "2") txt[$i]="?" ;;
+      "?") txt[$i]="2" ;;
+      "4") txt[$i]="p" ;;
+      "p") txt[$i]="4" ;;
+      "-") txt[$i]="L" ;;
+      "L") txt[$i]="-" ;;
+      esac
+      txtofus+="${txt[$i]}"
+    done
+    echo "$txtofus" | rev
+  }
+  
+# // Exporint IP AddressInformation
+
+# // Clear Data
+clear
+clear && clear && clear
+clear;clear;clear
+
+  # // Banner
+
+###### IZIN SC 
+
+veryfy_fun () {
 [[ ! -d ${IVAR} ]] && touch ${IVAR}
 [[ ! -d ${SCPT_DIR} ]] && mkdir ${SCPT_DIR}
 unset ARQ
@@ -27,59 +96,46 @@ esac
 mv -f $HOME/$1 ${ARQ}/$1
 chmod +x ${ARQ}/$1
 }
-ofus() {
-    unset server
-    server=$(echo ${txt_ofuscatw} | cut -d':' -f1)
-    unset txtofus
-    number=$(expr length $1)
-    for ((i = 1; i < $number + 1; i++)); do
-        txt[$i]=$(echo "$1" | cut -b $i)
-        case ${txt[$i]} in
-            ".") txt[$i]="C" ;;
-            "C") txt[$i]="." ;;
-            "3") txt[$i]="@" ;;
-            "@" ) txt[$i]="3" ;;
-            "4") txt[$i]="9" ;;
-            "9") txt[$i]="4" ;;
-            "6") txt[$i]="P" ;;
-            "P") txt[$i]="6" ;;
-            "L") txt[$i]="K" ;;
-            "K") txt[$i]="L" ;;
-        esac
-        txtofus+="${txt[$i]}"
-    done
-    echo "$txtofus" | rev
-}
-error_fun() {
-    msg -bar2 && msg -verm "ERROR entre VPS<-->GENERADOR (Port 81 TCP)" && msg -bar2
-    [[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
-    exit 1
-}
 
-invalid_key() {
-    msg -bar2 && msg -verm "  Code Invalido -- #¡Key Invalida#! " && msg -bar2
-    [[ -e $HOME/lista-arq ]] && rm $HOME/lista-arq
-    rm -rf lista-arq
-    exit 1
+figlet " DARNIXMX " | boxes -d stone -p a2v1 | sed 's/\(.\)/\x1b[1;37m\1\x1b[0m/g'
+read -p $'\033[1;97;102mINGRESA TU CLAVE\033[0m ' Key
+[[ ! $Key ]] && {
+echo -e "\033[1;36m--------------------------------------------------------------------\033[0m"
+echo -e "\033[1;33mKey inválida!"
+echo -e "\033[1;36m--------------------------------------------------------------------\033[0m"
+exit
 }
+meu_ip () {
+MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+MIP2=$(wget -qO- ipv4.icanhazip.com)
+[[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
+echo "$IP" > /usr/bin/vendor_code
+}
+meu_ip
+text="COMPILANDO CLAVE DE ACCESO "
+color="\033[1;37m"  # Blanco
 
-
-while [[ ! $Key ]]; do
-    msg -bar2 && msg -ne "\033[1;93m          >>> 𝕀ℕ𝔾ℝ𝔼𝕊𝔼 𝕊𝕌 𝕂𝔼𝕐 𝔸𝔹𝔸𝕁𝕆 <<<\n   \033[1;37m" && read Key
-    tput cuu1 && tput dl1
+for ((i = 0; i < ${#text}; i++)); do
+    echo -n -e "${color}${text:$i:1}"
+    sleep 0.1  # Ajusta este valor según tu preferencia para el retraso entre letras
 done
-msg -ne "    # Verificando Key # : "
+echo -e "\033[0m"  # Restaura el color predeterminado al final
 cd $HOME
+
+#wget -O "$HOME/lista-arq" $(ofus "$Key")/$IP > /dev/null 2>&1
 wget -O $HOME/lista-arq $(ofus "$Key")/$IP >/dev/null 2>&1 && echo -e "\033[1;32m Ofus Correcto" || {
-    echo -e "\033[1;91m Ofus Incorrecto"
+echo -e "\033[1;91m Ofus Incorrecto"
+
     invalid_key
+
     exit
+
 }
 
+#IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
 IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$IP" >/usr/bin/venip
 sleep 1s
-#function_verify
-updatedb
+
 if [[ -e $HOME/lista-arq ]] && [[ ! $(cat $HOME/lista-arq | grep "Code de KEY Invalido!") ]]; then
     msg -bar2
     msg -verd "    $(source trans -b es:${id} "Ficheros Copiados" | sed -e 's/[^a-z -]//ig'): \e[97m[\e[93m@NIXON\e[97m]"
@@ -92,4 +148,62 @@ if [[ -e $HOME/lista-arq ]] && [[ ! $(cat $HOME/lista-arq | grep "Code de KEY In
         wget --no-check-certificate -O ${SCPinstal}/${arqx} ${IP}:81/${REQUEST}/${arqx} >/dev/null 2>&1 && verificar_arq "${arqx}" || error_fun
         tput cuu1 && tput dl1
         pontos+="."
+
     done
+[[ ! -e /usr/bin/trans ]] && wget -O /usr/bin/trans https://www.dropbox.com/s/l6iqf5xjtjmpdx5/trans?dl=0 &> /dev/null
+#mv -f /bin/http-server.py /bin/http-server.sh && chmod +x /bin/http-server.sh
+apt-get install bc -y &>/dev/null
+apt-get install screen -y &>/dev/null
+apt-get install nano -y &>/dev/null
+apt-get install curl -y &>/dev/null
+apt-get install netcat -y &>/dev/null
+#apt-get install apache2 -y &>/dev/null
+#sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
+#service apache2 restart > /dev/null 2>&1 &
+IVAR2="/etc/key-gerador"
+echo "$Key" > $IVAR2
+rm $HOME/lista-arq
+} || {
+echo -e "\033[1;36m--------------------------------------------------------------------\033[0m"
+echo -e "\033[1;33mKey Invalida!"
+echo -e "\033[1;36m--------------------------------------------------------------------\033[0m"
+}
+echo -ne "\033[0m"
+
+echo -e " "
+    #echo -e " \033[3;97;41m REGISTRANDO CONEXION IP SSH \033[0m" | pv -qL 10
+    echo -e "\033[0;97;41mREGISTRANDO CONEXION IP SSH\033[0m" | pv -qL 10
+
+      sleep 5  # Pausa de 5 segundos
+       echo -e "\e[0;97;42mEXITOSO\e[0m" | pv -qL 10
+       sleep 2
+       sudo mv /etc/SCRIPT /usr/bin/
+
+    clear
+    clear
+    MI=$(wget -qO- ifconfig.me)
+ipsaya=$(wget -qO- ipinfo.io/ip)
+
+data_ip="https://raw.githubusercontent.com/darnix1/vip/main/izin"
+
+checking_sc() {
+  # Comentar las líneas relacionadas con la verificación de la fecha de vencimiento
+  # useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
+  # if [[ $date_list < $useexp ]]; then
+  #   echo -ne
+  # else
+  cols=$(tput cols)
+text="INSTALACION EN CURSO:"
+padding=$(((cols - ${#text}) / 3))
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    echo -ne "\033[38;5;15;48;5;208m$(printf "%*s" $padding)${text}$(printf "%*s" $padding)\033[0m"
+    echo " "
+    #echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    echo " "
+    echo -e "\e[1;33m RESELLER: $(awk '{printf "%0s\n", $0}' /usr/bin/SCRIPT/message.txt) VERIFICADO \e[0m" | pv -qL 10
+    echo -e "            ${RED}PERMISO CONCEDIDO${NC}"  # Ajusta el mensaje según tus necesidades
+    echo -e "   \033[0;33mTu ip fue autorizado exitosamente.${NC}"
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    # exit
+  # fi
+}
