Update x

diff --git a/backup/x b/backup/x
--- a/backup/x
+++ b/backup/x
@@ -121,35 +121,16 @@ for ((i = 0; i < ${#text}; i++)); do
 done
 echo -e "\033[0m"  # Restaura el color predeterminado al final
 cd $HOME
-
-#wget -O "$HOME/lista-arq" $(ofus "$Key")/$IP > /dev/null 2>&1
-wget -O $HOME/lista-arq $(ofus "$Key")/$IP >/dev/null 2>&1 && echo -e "\033[1;32m Ofus Correcto" || {
-echo -e "\033[1;91m Ofus Incorrecto"
-
-    invalid_key
-
-    exit
-
-}
-
-#IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
-IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$IP" >/usr/bin/venip
+wget -O "$HOME/lista-arq" $(ofus "$Key")/$IP > /dev/null 2>&1
+IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
 sleep 1s
-
-if [[ -e $HOME/lista-arq ]] && [[ ! $(cat $HOME/lista-arq | grep "Code de KEY Invalido!") ]]; then
-    msg -bar2
-    msg -verd "    $(source trans -b es:${id} "Ficheros Copiados" | sed -e 's/[^a-z -]//ig'): \e[97m[\e[93m@NIXON\e[97m]"
-    REQUEST=$(ofus "$Key" | cut -d'/' -f2)
-    [[ ! -d ${SCPinstal} ]] && mkdir ${SCPinstal}
-    pontos="."
-    stopping="Descargando Ficheros"
-    for arqx in $(cat $HOME/lista-arq); do
-        msg -verm "${stopping}${pontos}"
-        wget --no-check-certificate -O ${SCPinstal}/${arqx} ${IP}:81/${REQUEST}/${arqx} >/dev/null 2>&1 && verificar_arq "${arqx}" || error_fun
-        tput cuu1 && tput dl1
-        pontos+="."
-
-    done
+[[ -e $HOME/lista-arq ]] && {
+REQUEST=$(ofus "$Key" |cut -d'/' -f2)
+for arqx in `cat $HOME/lista-arq`; do
+echo -ne "\033[38;5;15;48;5;208mCONEXION: \033[0m"
+wget -O $HOME/$arqx ${IP}:81/${REQUEST}/${arqx} > /dev/null 2>&1 && echo -e "\033[1;31m- \033[1;32mExitosa !" || { echo -e "\033[0;97;41mFallida (Saliendo)\033[0m" | pv -qL 10; exit 1; }
+[[ -e $HOME/$arqx ]] && veryfy_fun $arqx
+done
 [[ ! -e /usr/bin/trans ]] && wget -O /usr/bin/trans https://www.dropbox.com/s/l6iqf5xjtjmpdx5/trans?dl=0 &> /dev/null
 #mv -f /bin/http-server.py /bin/http-server.sh && chmod +x /bin/http-server.sh
 apt-get install bc -y &>/dev/null
@@ -163,7 +144,11 @@ apt-get install netcat -y &>/dev/null
 IVAR2="/etc/key-gerador"
 echo "$Key" > $IVAR2
 rm $HOME/lista-arq
-
+} || {
+echo -e "\033[1;36m--------------------------------------------------------------------\033[0m"
+echo -e "\033[1;33mKey Invalida!"
+echo -e "\033[1;36m--------------------------------------------------------------------\033[0m"
+}
 echo -ne "\033[0m"
 
 echo -e " "
@@ -181,6 +166,28 @@ echo -e " "
 ipsaya=$(wget -qO- ipinfo.io/ip)
 
 data_ip="https://raw.githubusercontent.com/darnix1/vip/main/izin"
+
+checking_sc() {
+  # Comentar las líneas relacionadas con la verificación de la fecha de vencimiento
+  # useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
+  # if [[ $date_list < $useexp ]]; then
+  #   echo -ne
+  # else
+  cols=$(tput cols)
+text="INSTALACION EN CURSO:"
+padding=$(((cols - ${#text}) / 3))
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    echo -ne "\033[38;5;15;48;5;208m$(printf "%*s" $padding)${text}$(printf "%*s" $padding)\033[0m"
+    echo " "
+    #echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    echo " "
+    echo -e "\e[1;33m RESELLER: $(awk '{printf "%0s\n", $0}' /usr/bin/SCRIPT/message.txt) VERIFICADO \e[0m" | pv -qL 10
+    echo -e "            ${RED}PERMISO CONCEDIDO${NC}"  # Ajusta el mensaje según tus necesidades
+    echo -e "   \033[0;33mTu ip fue autorizado exitosamente.${NC}"
+    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
+    # exit
+  # fi
+}
 
 checking_sc() {
   # Comentar las líneas relacionadas con la verificación de la fecha de vencimiento
