Update xd

diff --git a/backup/xd b/backup/xd
--- a/backup/xd
+++ b/backup/xd
@@ -40,7 +40,7 @@ inst_components () {
 [[ $(dpkg --get-selections|grep -w "zip"|head -1) ]] || apt-get install zip -y &>/dev/null
 [[ $(dpkg --get-selections|grep -w "apache2"|head -1) ]] || {
  apt-get install apache2 -y &>/dev/null
- sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
+ #sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
  service apache2 restart > /dev/null 2>&1 &
  }
 }
@@ -149,10 +149,37 @@ msg -bar2 && msg -verm "$(source trans -b pt:${id} "Esta Chave Era de Outro Serv
 exit 1
 }
 invalid_key () {
-msg -bar2 && msg -verm "Key Failed! " && msg -bar2
-[[ -e $HOME/lista-arq ]] && rm $HOME/lista-arq
-exit 1
+[[ -e $HOME/lista-arq ]] && list_fix="$(cat < $HOME/lista-arq)" || list_fix=''
+[[ "$list_fix" = "KEY INVALIDA!" ]] && {
+IiP="$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
+cheklist="$(curl -sSL $IiP:81/dani/checkIP.log)"
+chekIP="$(echo -e "$cheklist" | grep ${Key} | awk '{print $3}')"
+chekDATE="$(echo -e "$cheklist" | grep ${Key} | awk '{print $7}')"
+msg -bar3
+echo ""
+[[ ! -z ${chekIP} ]] && { 
+varIP=$(echo ${chekIP}| sed 's/[1-5]/X/g')
+msg -verm " KEY USADA POR IP : ${varIP} \n FECHA: ${chekDATE} ! "
+echo ""
+msg -bar3
+} || {
+echo -e "    PRUEBA COPIAR BIEN TU KEY "
+[[ $(echo "$(ofus "$Key"|cut -d'/' -f2)" | wc -c ) = 18 ]] && echo -e "" || echo -e "\033[1;31m CONTENIDO DE LA KEY ES INCORRECTO"
+echo -e "   KEY NO COINCIDE CON EL CODEX DEL ADM "
+msg -bar3
+tput cuu1 && tput dl1
 }
+}
+#msg -bar2 && msg -verm "Key Failed! " && msg -bar2
+[[ -e $HOME/lista-arq ]] && rm $HOME/lista-arq
+echo -e "\033[1;37m DESEAS REINTENTAR CON OTRA KEY\033[1;32m.\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+echo -ne "\033[0;32m "
+read -p "  Responde [ s | n ] : " -e -i "s" x
+[[ $x = @(s|S|y|Y) ]] && funkey || {
+exit&&exit
+}
+}
+
 while [[ ! $Key ]]; do
 msg -ne "Script Key: " && read Key
 tput cuu1 && tput dl1
